<<<<<<< HEAD
repos:
  - repo: local
    hooks:
      - id: codeguard
        name: CodeGuard AI Review
        entry: python -m vcs.precommit
        language: system
=======
repos:
  - repo: local
    hooks:
      - id: codeguard
        name: CodeGuard AI Review
        entry: python -m vcs.precommit
        language: system
>>>>>>> 2b60f41b6be5557b36a1939eaf733b5d98f9da28
        types: [python]